---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: centos-6.5
    driver_config:
      box: chef/centos-6.5
      customize:
        memory: 768

suites:
  - name: server
    run_list:
      - recipe[dhcp::server]
    attributes: {}
    driver_config:
      network:
        - ["private_network", {ip: "192.168.33.31"}]
  - name: client
    run_list:
      - recipe[dhcp::client]
    attributes: {}
    driver_config:
      network:
        - ["private_network", {ip: "192.168.33.32"}]
